### ISSUE TITLE
Lingering non-unique key error

### ISSUE THREAD

**Issue by DuncanUszkay1** [DuncanUszkay1/ven#7]

**Comment by DuncanUszkay1** [comment]
react_devtools_backend.js:4045 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `TileMap`. See https://reactjs.org/link/warning-keys for more information.
    at ListItemButton (http://localhost:1212/renderer.dev.js:279924:83)
    at TileMap (http://localhost:1212/renderer.dev.js:395471:9)
    at div
    at http://localhost:1212/renderer.dev.js:597:66
    at Box (http://localhost:1212/renderer.dev.js:307768:72)
    at div
    at TabPanel (http://localhost:1212/renderer.dev.js:395298:13)
    at div
    at http://localhost:1212/renderer.dev.js:597:66
    at Box (http://localhost:1212/renderer.dev.js:307768:72)
    at div
    at http://localhost:1212/renderer.dev.js:597:66
    at Stack (http://localhost:1212/renderer.dev.js:291621:87)
    at MapEditor (http://localhost:1212/renderer.dev.js:394893:9)
    at div
    at http://localhost:1212/renderer.dev.js:597:66
    at Box (http://localhost:1212/renderer.dev.js:307768:72)
    at div
    at TabPanel (http://localhost:1212/renderer.dev.js:395298:13)
    at div
    at http://localhost:1212/renderer.dev.js:597:66
    at Box (http://localhost:1212/renderer.dev.js:307768:72)
    at div
    at http://localhost:1212/renderer.dev.js:597:66
    at Stack (http://localhost:1212/renderer.dev.js:291621:87)
    at Editor (http://localhost:1212/renderer.dev.js:394521:9)
    at App (http://localhost:1212/re
